### ISSUE TITLE
[Question] another use

### ISSUE THREAD

**Issue by aelisya** [TCB13/LoFloccus#12]
Hello i have a single question, if i use another software to connect myself to the local webdav, can i create another file without breaking floccus ? (i think about keepass webdav sync)

thanks

**Comment by TCB13** [comment]
Hello,

I wouldn't break floccus, however it won't work because due to security reasons the webdav server is restricted to a single directory and to *.xbel bookmarks files only.

Have a look at it here: https://github.com/TCB13/LoFloccus/blob/71037c508e3b20158b0ec23e082814f1fb17035a/LoFloccus.go#L303

**Comment by aelisya** [comment]
too bad thanks for the answer 👍

**Comment by TCB13** [comment]
> 
> 
> too bad thanks for the answer 👍

You can always edit it if you have the time. Replacing the line with the following should be enough for your use case. 

````
 if (request.RequestURI != "/") || (request.RequestURI == "/" && (request.Method != "HEAD" && request.Method != "PROPFIND")) { 
````

Since I also use KeePassXC I'm curious, why would you want to use this? This small program is also restricted to your localhost so no other computer would be able to access the WebDav server...

**Comment by aelisya** [comment]
> > too bad thanks for the answer 👍
> 
> You're welcome. You can always edit it if you have the time. Replacing the line with the following should be enough for your use case.
> 
> ```
>  if (request.RequestURI != "/") || (request.RequestURI == "/" && (request.Method != "HEAD" && request.Method != "PROPFIND")) { 
> ```
> 
> Since I also use KeePassXC I'm curious, why would you want to use this? This small program is also restricted to your localhost so no other computer would be able to access the WebDav server...

Actually it's beacause keepass have a mecanism to prevent sync conflict that isn't active on the file version, so the local webdav (who is on my sync folder) can enable this mecanism with a local file ^^)
