### ISSUE TITLE
"Could not open the UI file"

### ISSUE THREAD

**Issue by akwala** [TCB13/LoFloccus#3]
Kubuntu 18.04
Qt 5.12.3
go version go1.12 linux/amd64

Did the following after installing _Qt_ and _github.com/therecipe/qt_:

```
$ cd /path/to/cloned/LoFloccus
$ export QT_QPA_PLATFORM_PLUGIN_PATH=/path/to/Qt/5.12.3/gcc_64/plugins/  # to fix error: Could not find the Qt platform plugin "xcb" in ""
$ go run LoFloccus.go
2019/05/29 18:29:07 Could not open the UI file
exit status 1
```

The error message in the code is [here](https://github.com/TCB13/LoFloccus/search?q=Could+not+open+the+UI+file&unscoped_q=Could+not+open+the+UI+file). It's apparently trying to open `/path/to/cloned/LoFloccus/qml/LoFloccus.ui` which does exist, is owned by me and its permissions are 664.

**Comment by TCB13** [comment]
Hello, I believe the issue is related to how the file paths are treated when using `go run` vs a built solution with `qtdeploy`. I've reported this issue here: https://github.com/therecipe/qt/issues/850

In order to make it run properly via `go run LoFloccus.go` you need to replace `./` (that works just fine with `qtdeploy` builds) by `:/` like I did on the example.

**Comment by akwala** [comment]
@TCB13 Thanks. The qtdeploy build succeeded.

**Comment by TCB13** [comment]
@akwala since you're on something-Ubuntu that uses KDE, can you confirm if the tray icon / minimize to tray works as expected?

**Comment by akwala** [comment]
> @akwala since you're on something-Ubuntu that uses KDE, can you confirm if the tray icon / minimize to tray works as expected?

Yes, it does. Start minimized also works as expected. The tray icon menu appears when icon is right-clicked, which has been characteristic KDE behavior.

**Comment by TCB13** [comment]
Thank you for the feedback @akwala
